### ISSUE TITLE
Run server in all relevant environments

### ISSUE THREAD

**Issue by MiguelRodo** [MiguelRodo/ProjectVSCServer#1]
### Tasks

- [x] Run the server in WSL
- [x] Run the server inside an apptainer container
- [ ] Run the server on the HPC not in a container
- [x] Run the server inside an apptainer container on the HPC

**Comment by MiguelRodo** [comment]
### Run the server inside WSL

- This was easy, just run their setup code and run `code-server`

**Comment by MiguelRodo** [comment]
### Run the server inside an apptainer container

- This took some figuring out, but is not difficult to do
- It's running slowly, though
- I think it needs to be installed in a singularity image for me to use it
  - Steps to use in an apptainer container:
    - Create a Dockerfile
      - Probably just plain Ubuntu
      - Contents
        - From Ubuntu
        - Install VSC server (I don't think anything else?)
    - Create apptainer from Dockerfil
      - How?
        - These instructions didn't work: https://medium.com/@dcat52/making-your-first-container-81b832d82a6f
        - It does work, as long as the definition file ends in `.def`
          - Not clear if this is a general rule, or if this has to be done just because of the way the command was written

**Comment by MiguelRodo** [comment]
## Run the server on the HPC

- To do this, I can either run it directly on the server or else inside a Singularity container on the server

**Comment by MiguelRodo** [comment]
This link gives instructions for installing on the cluster itself:
https://github.com/microsoft/vscode-remote-release/issues/1722#issuecomment-1267026565
